trying again

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -24,3 +24,6 @@ jobs:
       - name: Run Tests
         run: | 
           make -f makefiles/RunTests.mk
+          if [[ $? -eq 1 ]]; then
+            echo "::error::Tests Failed"
+          fi
